[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "."

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/main/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
